docs: add and improve GitHub integration guide
coderabbitai/coderabbit-docs pull request #121
Opened 2024-10-29 14:32 UTC by tyaga001

2024-10-30 14:49 UTC, aravindputrevu requested changes

2024-10-30 14:49 UTC, aravindputrevu commented on docs/guides/commands.md
> +sidebar_label: All Commands
Let us revamp the sidebar and these titles in the next PR. So, we can keep this specific one as is.

2024-10-30 14:49 UTC, aravindputrevu commented on docs/platforms/azure-devops.md
> +title: Use CodeRabbit with Azure DevOps
But actually it is integration @tyaga001 not using like database.

2024-10-30 14:49 UTC, aravindputrevu commented on docs/platforms/github-com.md
> +We at [CodeRabbit](https://www.coderabbit.ai/), has lived through this problem and with the advent of Generative AI, code generation models, we realised we could help improve this end of developer's
Let us remove all of it

2024-10-30 14:49 UTC, aravindputrevu commented on docs/platforms/github-com.md
> +## Integrating with GitHub
may be repetitive heading

2024-10-30 15:51 UTC, tyaga001 commented on docs/guides/commands.md
> +sidebar_label: All Commands
reverted

2024-10-30 15:56 UTC, tyaga001 commented on docs/guides/delete-account.md
> +![How-to-Delete-CodeRabbit-Account](/img/guides/delete_account_dark.png#gh-dark-mode-only)
@aravindputrevu, it looks like it's not so, as I didn't change the path.

2024-10-31 10:08 UTC, tyaga001 commented on docs/platforms/github-com.md
> +![How CodeRabbit Works](/img/integrations/how-codeRabbit-works.png)
No, It's correct. It's the same across all the pages, and I tried static. It's failing locally.
![image](https://github.com/user-attachments/assets/10b7792f-1c41-4210-b7a5-744b0a1ed400)

2024-10-31 16:31 UTC, aravindputrevu commented on docs/guides/delete-account.md
> +![How-to-Delete-CodeRabbit-Account](/img/guides/delete_account_dark.png#gh-dark-mode-only)
@coderabbitai it looks like you are wrong here, images are referred in `/img` and not `/static`.

2024-11-01 15:52 UTC, tyaga001 commented
@aravindputrevu can we merge?

2024-11-05 09:47 UTC, aravindputrevu approved these changes

2024-11-05 14:54 UTC, closed without merging